<a href="https://colab.research.google.com/github/davidfashokun/SRS_Req_Classification_Promise_Phi3.5/blob/main/srs_req_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q -U transformers accelerate peft bitsandbytes datasets trl
import pandas as pd
from datasets import Dataset
import io

# Manually parse the ARFF file content to handle string attributes
arff_file_path = "/content/dataset/PROMISE_exp.arff"
data_lines = []
attributes = []
in_data_section = False

with open(arff_file_path, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if line.lower().startswith('@data'):
            in_data_section = True
            continue
        if line.lower().startswith('@attribute') and not in_data_section:
            # Parse attribute line to get column names
            parts = line.split()
            attr_name = parts[1]
            attributes.append(attr_name)
        elif in_data_section and line:
            data_lines.append(line)

# Create a string buffer for pandas to read the data section
data_string = io.StringIO("\n".join(data_lines))

# Read the data into a DataFrame, assuming comma separation. If this fails, we will need to inspect the delimiter.
df = pd.read_csv(data_string, header=None, names=attributes)

# Format into instruction-response pairs
def format_example(row):
    return {
        "text": f"""<|user|>
Classify the following software requirement into one of these categories:
Functional (F), Usability (US), Security (SE), Operational (O), Performance (PE),
Look & Feel (LF), Maintainability (MN), Portability (PO), Legal (L), Fault Tolerance (FT), Scalability (SC), Availability (A).

Requirement: {row['RequirementText']}<|end|>
<|assistant|>
{row['_class_']}<|end|>"""
    }

dataset = Dataset.from_pandas(df).map(format_example)
dataset = dataset.train_test_split(test_size=0.2)

Map:   0%|          | 0/969 [00:00<?, ? examples/s]

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

model_id = "microsoft/Phi-3.5-mini-instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

[transformers] This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.
WARNING:transformers_modules.microsoft.Phi_hyphen_3_dot_5_hyphen_mini_hyphen_instruct.2fe192450127e6a83f7441aef6e3ca586c338b77.modeling_phi3:`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
WARNING:transformers_modules.microsoft.Phi_hyphen_3_dot_5_hyphen_mini_hyphen_instruct.2fe192450127e6a83f7441aef6e3ca586c338b77.modeling_phi3:Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [3]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# You'll see something like: ~0.5% of params are trainable

trainable params: 3,145,728 || all params: 3,824,225,280 || trainable%: 0.0823

In [8]:
from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./phi3.5-promise",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=False,
    bf16=True,
    logging_steps=10,
    save_strategy="epoch",
    optim="paged_adamw_8bit",
    eval_strategy="epoch", # new args below
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Attach tokenizer to the model directly if SFTTrainer doesn't accept it as an argument
model.tokenizer = tokenizer

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    args=training_args,
    # tokenizer=tokenizer,  # Removed as it's causing the TypeError
    # dataset_text_field="text",  # Removed as it's causing a TypeError
    # max_length=512, # Removed as it's causing the TypeError
)

trainer.train()

Adding EOS to train dataset:   0%|          | 0/775 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/775 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/194 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/194 [00:00<?, ? examples/s]

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
WARNING:transformers_modules.microsoft.Phi_hyphen_3_dot_5_hyphen_mini_hyphen_instruct.2fe192450127e6a83f7441aef6e3ca586c338b77.modeling_phi3:You are not running the flash-attention implementation, expect numerical differences.

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TrainOutput(global_step=291, training_loss=2.2677412119108378, metrics={'train_runtime': 3629.8738, 'train_samples_per_second': 0.641, 'train_steps_per_second': 0.08, 'total_flos': 6516650120896512.0, 'train_loss': 2.2677412119108378})

In [15]:
trainer.evaluate()

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

{'eval_loss': 11.131410598754883}

In [18]:
from sklearn.metrics import classification_report
import torch

model.eval()
predictions, true_labels = [], []

for example in dataset["test"]:
    # Build prompt without the answer
    prompt = example["text"].split("<|assistant|>")[0] + "<|assistant|>\n"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output = model.generate(**inputs, max_new_tokens=10, do_sample=False, use_cache=False)

    pred = tokenizer.decode(output[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
    true = example["text"].split("<|assistant|>")[1].replace("<|end|>", "").strip()

    predictions.append(pred)
    true_labels.append(true)

print(classification_report(true_labels, predictions))

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

                                                                precision    recall  f1-score   support

                                                             A       0.00      0.00      0.00       6.0
                       AddAdd Ext Ext Extmer Ext Ext Moore Ext       0.00      0.00      0.00       0.0
                Adrilookup Ext Ext Moore Ext Ext Ext Leo siehe       0.00      0.00      0.00       0.0
               Dictionary Ext siehe Extwohl ужеwohl Extmer Ext       0.00      0.00      0.00       0.0
                       Ext Ext Ext Ext Ext Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                   Ext Ext Ext Ext Ext Ext Ext Ext Ext genannt       0.00      0.00      0.00       0.0
                     Ext Ext Ext Ext Ext Ext Ext Ext Extlookup       0.00      0.00      0.00       0.0
                     Ext Ext Ext Ext Ext Moore Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                     Ext Ext Ext Ext Moore Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                     Ext Ext Ext Moore Ext Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Ext Moore Ext Ext Ext Ext Ext genannt       0.00      0.00      0.00       0.0
                     Ext Ext Ext Moore Ext Ext Ext Ext уже Ext       0.00      0.00      0.00       0.0
                      Ext Ext Ext Moore Ext Ext Ext Ext ужеjav       0.00      0.00      0.00       0.0
                    Ext Ext Ext Moore Ext Ext Ext Extcamerajav       0.00      0.00      0.00       0.0
                      Ext Ext Ext Moore Ext Ext Ext Extjav Ext       0.00      0.00      0.00       0.0
                 Ext Ext Ext Moore Ext Ext Ext Extlookup Moore       0.00      0.00      0.00       0.0
                      Ext Ext Ext Moore Ext Ext Ext Extmer Ext       0.00      0.00      0.00       0.0
                   Ext Ext Ext Moore Ext Ext Ext Moore Ext Ext       0.00      0.00      0.00       0.0
               Ext Ext Ext Moore Ext Ext Ext Moore Ext genannt       0.00      0.00      0.00       0.0
                     Ext Ext Ext Moore Ext Ext Ext уже Ext Zar       0.00      0.00      0.00       0.0
                      Ext Ext Ext Moore Ext Ext Ext ужеjav Ext       0.00      0.00      0.00       0.0
                 Ext Ext Ext Moore Ext Ext Extcamera siehe Ext       0.00      0.00      0.00       0.0
                      Ext Ext Ext Moore Ext Ext Extjav Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Ext Moore Ext Ext Extlookup Moore Ext       0.00      0.00      0.00       0.0
                   Ext Ext Ext Moore Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
                       Ext Ext Ext Moore Extjav Extmer Ext Ext       0.00      0.00      0.00       0.0
              Ext Ext Ext Moore Extjav ExtmerUITableView siehe       0.00      0.00      0.00       0.0
                   Ext Ext Ext Moore Extjav siehe Extcameramer       0.00      0.00      0.00       0.0
                     Ext Ext Ext ужеjav Ext Extmer siehecamera       0.00      0.00      0.00       0.0
                     Ext Ext Extjav Moore Ext уже siehe ужеmer       0.00      0.00      0.00       0.0
             Ext Ext Extjav Moorecamera Dictionary Ext Ext Ext       0.00      0.00      0.00       0.0
                      Ext Ext Extmer Ext Ext Ext Ext Moore Ext       0.00      0.00      0.00       0.0
                    Ext Ext Extmer Ext Ext Ext Extlookup Moore       0.00      0.00      0.00       0.0
                      Ext Ext Extmer Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
                          Ext Ext Extmer Ext Extmer Ext Extmer       0.00      0.00      0.00       0.0
                    Ext Ext Extmer Ext Extmer Ext Historia Ext       0.00      0.00      0.00       0.0
                    Ext Ext Extmer Extcameramer Ext:\ complete       0.00      0.00      0.00       0.0
                           Ext Ext Extmer Extjav Extmer Extmer       0.00      0.00      0.00       0.0
                       Ext Ext Extmerритор Extmer Extcameramer       0.00      0.00      0.00       0.0
                     Ext Ext Moore Ext Ext Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                   Ext Ext Moore Ext Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Ext Moore Extlookup Ext       0.00      0.00      0.00       0.0
                    Ext Ext Moore Ext Ext Ext Moore Extmer Ext       0.00      0.00      0.00       0.0
                   Ext Ext Moore Ext Ext Moore Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Moore Ext Ext Ext Moore       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Moore Ext Ext Extlookup       0.00      0.00      0.00       0.0
                    Ext Ext Moore Ext Ext Moore Ext Ext Extmer       0.00      0.00      0.00       0.0
                    Ext Ext Moore Ext Ext Moore Ext Ts Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Moore Ext siehe Ext Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Moore Extannt Moore Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Ext Moore Extannt Mooreannt       0.00      0.00      0.00       0.0
                  Ext Ext Moore Ext Ext Moore Extannt siehemer       0.00      0.00      0.00       0.0
               Ext Ext Moore Ext Ext Moore Extlookup Moore Ext       0.00      0.00      0.00       0.0
                 Ext Ext Moore Ext Moore Ext Ext Ext Moore Ext       0.00      0.00      0.00       0.0
                  Ext Ext Moore Ext Moore ExtAdd Moore Ext Ext       0.00      0.00      0.00       0.0
             Ext Ext Moore Ext Moore Extcamera Moorejav offici       0.00      0.00      0.00       0.0
                     Ext Ext Moore Ext ужеjavannt Extjav Moore       0.00      0.00      0.00       0.0
                   Ext Ext Moore Moore Ext Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                     Ext Extjavfield Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
         Ext ExtmerUITableView huvudmer Ext ExtUITableView Ext       0.00      0.00      0.00       0.0
Ext ExtmerUITableView huvudmer sieheUITableViewUITableView Ext       0.00      0.00      0.00       0.0
                     Ext ExtmerUITableViewmer mistmermeractmer       0.00      0.00      0.00       0.0
                  Extlookup Extритор Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
            Extlookup Moore siehecamera werk Ext Ext Ext Moore       0.00      0.00      0.00       0.0
                                                             F       0.00      0.00      0.00      89.0
                                                            FT       0.00      0.00      0.00       5.0
                                                             L       0.00      0.00      0.00       2.0
                                                            LF       0.00      0.00      0.00       9.0
                                                            MN       0.00      0.00      0.00       5.0
                      MooreAdd siehe Ext Extmer Ext:\mer siehe       0.00      0.00      0.00       0.0
                                                             O       0.00      0.00      0.00      16.0
                                                            PE       0.00      0.00      0.00      13.0
                                                            PO       0.00      0.00      0.00       2.0
                  ProblemAdd Ext Ext Ext Moore Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                   ProblemAdd Ext Extmer Ext Ext Moore Ext Ext       0.00      0.00      0.00       0.0
                ProblemAdd Ext siehe Ext Zar Moore Ext Ext Ext       0.00      0.00      0.00       0.0
               Problemlookup Ext Ext Ext Moore Ext Ext Ext Ext       0.00      0.00      0.00       0.0
     Problemlookupcamera sieheUITableView Ext Ext Moore ExtAdd       0.00      0.00      0.00       0.0
               Problemlookupcameralookupcameramer Extmermermer       0.00      0.00      0.00       0.0
                  Problemmer Extmermer siehecameramermerlookup       0.00      0.00      0.00       0.0
                                                            SC       0.00      0.00      0.00       3.0
                                                            SE       0.00      0.00      0.00      29.0
                   UEFA ExtXX Moorecamera siehecameraAddjavAdd       0.00      0.00      0.00       0.0
                    UEFAcamerameranntcameramer Extcameramermer       0.00      0.00      0.00       0.0
                                                            US       0.00      0.00      0.00      15.0
  camera Dictionary Extannt Extanntmer offici sieheUITableView       0.00      0.00      0.00       0.0
                camera Ext Ext Ext Moore Ext Ext Ext Moore Ext       0.00      0.00      0.00       0.0
                     camera Ext Ext Extmer Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
                  camera Ext Ext Moore Extmer Extcameramer Ext       0.00      0.00      0.00       0.0
               camera Ext ExtmerUITableViewujmerabordcameramer       0.00      0.00      0.00       0.0
                camera Ext ExtmerUITableViewujmercameramer Ext       0.00      0.00      0.00       0.0
           camera trivial Ext Ext Extjav Moorecamera juego Ext       0.00      0.00      0.00       0.0
                  cameramer Ext ExtmerUITableViewarbemermermer       0.00      0.00      0.00       0.0
                cameramer Ext ExtmerUITableViewighcameramermer       0.00      0.00      0.00       0.0
            cameramer Ext:\ mist Moore Moorewohl genanntcamera       0.00      0.00      0.00       0.0
                      cameramer Extcamera siehe Zaranntmerannt       0.00      0.00      0.00       0.0
              cameramer Extcamera siehecameramerlookupjav gare       0.00      0.00      0.00       0.0
                 cameramer Extcameragradient:\mermeract offici       0.00      0.00      0.00       0.0
               cameramer Extcameramer Ext ужеUITableViewmermer       0.00      0.00      0.00       0.0
                cameramer Extcameramer Extcameracamera Ext Ext       0.00      0.00      0.00       0.0
             cameramer Extcameraритор Extmer ExtUITableViewact       0.00      0.00      0.00       0.0
       cameramer Extmer ExtUITableView sieheUITableViewmer Ext       0.00      0.00      0.00       0.0
 cameramer siehecameramer Historiacamera siehe genannt genannt       0.00      0.00      0.00       0.0
complete completecamera siehecamera Dictionary Ext Ext Extannt       0.00      0.00      0.00       0.0
     complete completecamera siehecameramer Ext trivialmer Ext       0.00      0.00      0.00       0.0
    complete completecamerajavcamera siehe Ext Ext Moore Moore       0.00      0.00      0.00       0.0
         complete completecamerajavätt mistmer уже completemer       0.00      0.00      0.00       0.0
          complete completecameramer Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
      complete completecameramer Ext executesmer Ext Ext Moore       0.00      0.00      0.00       0.0
        complete completelookupcameramer Ext Ext siehe Ext Ext       0.00      0.00      0.00       0.0
                 completeAdd Adri Extmer Ext Ext Moore Ext уже       0.00      0.00      0.00       0.0
                 completeAdd Ext Ext Moore Ext Ext Ext Ext Ext       0.00      0.00      0.00       0.0
 completelookupcameraUITableView siehemer genannt genanntjav:\       0.00      0.00      0.00       0.0
             gabelookup siehe siehelookupmerlookupactmerlookup       0.00      0.00      0.00       0.0
                      genannt Ext Ext Extjav Ext Extmer ExtAdd       0.00      0.00      0.00       0.0
    genannt Extjav Moore mist Moore Moore genannt genannt gare       0.00      0.00      0.00       0.0
        genannt Extjav Moorecamera Dictionarywohl Extmer Moore       0.00      0.00      0.00       0.0
           genannt Extjav siehe Moore Extjav Moorecamera juego       0.00      0.00      0.00       0.0
  genannt Extjav siehe Moore genannt Moore siehe Moore genannt       0.00      0.00      0.00       0.0
             genannt Moore Ext Ext Ext Ext Ext genannt Ext Ext       0.00      0.00      0.00       0.0
           genannt Moorejav officimermer siehemer genannt gare       0.00      0.00      0.00       0.0
                   genanntAdd Ext Ext Ext ужеjav Ext Ext Moore       0.00      0.00      0.00       0.0
                       genanntAdd Ext Ext Ext ужеjavjavAdd Ext       0.00      0.00      0.00       0.0
                genanntAdd Moore Ext Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
              includmermer siehecamerameranntmer juego trivial       0.00      0.00      0.00       0.0
    lookuplookup trivial Ext Extjav Moorecamera Dictionary Ext       0.00      0.00      0.00       0.0
                  mer Extcameramer Ext ExtmerUITableViewmermer       0.00      0.00      0.00       0.0
              mer siehecameramer Ext Ext ExtmerUITableView уже       0.00      0.00      0.00       0.0
             mermer siehecameramer siehe ExtmerUITableView шта       0.00      0.00      0.00       0.0
                           mermer:\ siehemer Zar ужеmer Extmer       0.00      0.00      0.00       0.0
                            mermer:\cameramermermer уже ужеmer       0.00      0.00      0.00       0.0
               mermercamera invece siehemercameracameramer Ext       0.00      0.00      0.00       0.0
                           mermermermer уже ужеmercameramermer       0.00      0.00      0.00       0.0
                     mermermermercamera invecemermer ужеcamera       0.00      0.00      0.00       0.0
             performed Ext Ext Moore Ext Ext Moore Ext Ext Ext       0.00      0.00      0.00       0.0
    performed Ext Ext Moore Moorecamera Dictionary Ext Ext Ext       0.00      0.00      0.00       0.0
               performedmer Extcameracamera Ext Ext Extjav Ext       0.00      0.00      0.00       0.0
               siehe Problem Ext Ext Ext Moore Ext Ext Ext Ext       0.00      0.00      0.00       0.0
           siehe mistmerjav huvud Ressourcecameramer Extcamera       0.00      0.00      0.00       0.0
                     siehe siehemermerôt mistlookup Zarmer уже       0.00      0.00      0.00       0.0
               sieheUITableViewmerAddmer Ext Ext Moore Ext Ext       0.00      0.00      0.00       0.0
                sieheUITableViewmermermermer siehe siehemermer       0.00      0.00      0.00       0.0
                          siehemermermermermer siehemercamera→       0.00      0.00      0.00       0.0
                    ît уже Moore Ext Ext Ext Ext Moore Ext Ext       0.00      0.00      0.00       0.0

                                                      accuracy                           0.00     194.0
                                                     macro avg       0.00      0.00      0.00     194.0
                                                  weighted avg       0.00      0.00      0.00     194.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [19]:
!zip -r phi3.5-promise-final.zip ./phi3.5-promise-final
from google.colab import files
files.download("phi3.5-promise-final.zip")

  adding: phi3.5-promise-final/ (stored 0%)
  adding: phi3.5-promise-final/chat_template.jinja (deflated 61%)
  adding: phi3.5-promise-final/tokenizer.json (deflated 85%)
  adding: phi3.5-promise-final/adapter_config.json (deflated 58%)
  adding: phi3.5-promise-final/training_args.bin (deflated 53%)
  adding: phi3.5-promise-final/tokenizer_config.json (deflated 46%)
  adding: phi3.5-promise-final/README.md (deflated 65%)
  adding: phi3.5-promise-final/adapter_model.safetensors (deflated 8%)

In [20]:
# Save the LoRA adapter
trainer.save_model("./phi3.5-promise-final")

# Merge LoRA into base model so you can use it standalone
from peft import PeftModel
from transformers import AutoModelForCausalLM, BitsAndBytesConfig # Import necessary classes
import torch

# Re-define bnb_config for robustness if it's not globally available within this cell's scope
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

# Re-load the original base model
base_model = AutoModelForCausalLM.from_pretrained(
    model_id, # model_id is 'microsoft/Phi-3.5-mini-instruct' from previous cell
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

# Load the PeftModel (adapter) onto the base model
merged_model = PeftModel.from_pretrained(base_model, "./phi3.5-promise-final")

# Merge the LoRA weights into the base model and unload the adapters
merged_model = merged_model.merge_and_unload()

# Save the merged model and tokenizer
merged_model.save_pretrained("./phi3.5-promise-merged", save_original_format=True)
tokenizer.save_pretrained("./phi3.5-promise-merged")

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/peft/peft_model.py:622: UserWarning: Found missing adapter keys while loading the checkpoint: ['base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.1.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.1.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.2.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.2.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.3.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.3.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.4.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.4.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.5.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.5.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.6.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.6.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.7.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.7.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.8.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.8.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.9.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.9.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.10.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.10.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.11.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.11.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.12.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.12.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.13.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.13.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.14.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.14.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.15.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.15.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.16.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.16.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.17.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.17.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.18.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.18.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.19.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.19.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.20.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.20.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.21.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.21.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.22.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.22.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.23.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.23.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.24.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.24.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.25.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.25.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.26.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.26.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.27.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.27.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.28.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.28.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.29.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.29.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.30.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.30.self_attn.o_proj.lora_B.default.weight', 'base_model.model.model.layers.31.self_attn.o_proj.lora_A.default.weight', 'base_model.model.model.layers.31.self_attn.o_proj.lora_B.default.weight'].
  warnings.warn(warn_message)
/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:373: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(

AttributeError: 'list' object has no attribute 'keys'